//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Abonne
    {
        public int Id { get; set; }
        public string Libelle { get; set; }
        public int IdCRM { get; set; }
        public string Email { get; set; }
        public int Type { get; set; }
    }
}
