//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataField
    {
        public int ID { get; set; }
        public string Key { get; set; }
        public string Desc { get; set; }
        public string Type { get; set; }
    
        public virtual DataIconFieldGroup DataIconFieldGroup { get; set; }
    }
}
