//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DynMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DynMenu()
        {
            this.DynMenu1 = new HashSet<DynMenu>();
            this.AspNetRoles = new HashSet<AspNetRoles>();
        }
    
        public int Id { get; set; }
        public string Libelle { get; set; }
        public string Url { get; set; }
        public string Icon { get; set; }
        public int Ordre { get; set; }
        public Nullable<int> fk_menu { get; set; }
        public string Titre { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DynMenu> DynMenu1 { get; set; }
        public virtual DynMenu DynMenu2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AspNetRoles> AspNetRoles { get; set; }
    }
}
