//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Extension
    {
        public int id { get; set; }
        public string ext { get; set; }
        public int type { get; set; }
    
        public virtual TypeFichier TypeFichier { get; set; }
    }
}
