//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FormsEntities : DbContext
    {
        public FormsEntities()
            : base("name=FormsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Abonne> Abonne { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Civilite> Civilite { get; set; }
        public virtual DbSet<DynMenu> DynMenu { get; set; }
        public virtual DbSet<Etat> Etat { get; set; }
        public virtual DbSet<Extension> Extension { get; set; }
        public virtual DbSet<ObjectMail> ObjectMail { get; set; }
        public virtual DbSet<ORGANISATION> ORGANISATION { get; set; }
        public virtual DbSet<SendedMail> SendedMail { get; set; }
        public virtual DbSet<TypeFichier> TypeFichier { get; set; }
        public virtual DbSet<UNITE> UNITE { get; set; }
        public virtual DbSet<user_history> user_history { get; set; }
        public virtual DbSet<FormGroup> FormGroup { get; set; }
        public virtual DbSet<DataField> DataField { get; set; }
        public virtual DbSet<DataIconFieldGroup> DataIconFieldGroup { get; set; }
        public virtual DbSet<Section> Section { get; set; }
        public virtual DbSet<Form> Form { get; set; }
        public virtual DbSet<FieldGroup> FieldGroup { get; set; }
        public virtual DbSet<Question> Question { get; set; }
        public virtual DbSet<QType> QType { get; set; }
        public virtual DbSet<PreparedGroupField> PreparedGroupField { get; set; }
        public virtual DbSet<PreparedQuestion> PreparedQuestion { get; set; }
        public virtual DbSet<PreparedFiled> PreparedFiled { get; set; }
    }
}
