//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PreparedGroupField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PreparedGroupField()
        {
            this.PreparedFiled = new HashSet<PreparedFiled>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PreparedQuestionId { get; set; }
    
        public virtual PreparedQuestion PreparedQuestion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PreparedFiled> PreparedFiled { get; set; }
    }
}
