//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Forms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendedMail
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string Fk_User { get; set; }
        public int Fk_ObejctMail { get; set; }
        public int IdMail { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual ObjectMail ObjectMail { get; set; }
    }
}
